### PR TITLE
technicrefill_RE_charge is nothing l think

### PR DESCRIPTION
**Pull request by HybridDog**
technicrefill_RE_charge wasn't declared, so l commented it

### CODE REVIEW

**Comment by ExcaliburZero** [comment]
What does ''technicrefill_RE_charge'' normally do? I copied it from a Technic tool, but I wasn't sure exactly what its function was.

**Comment by HybridDog** [comment]
it's called technic.refill_RE_charge and not technicrefill_RE_charge
https://github.com/minetest-technic/technic/blob/master/technic/tools/mining_lasers.lua#L158
https://github.com/minetest-technic/technic/blob/master/technic/helpers.lua#L26

and it looks like it's a function which isn't used
but for some reason it's added to tools and the battery

grep -r technic.refill_RE_charge

> technic/machines/register/battery_box.lua: on_refill = technic.refill_RE_charge,
> technic/items.lua:  on_refill = technic.refill_RE_charge,
> technic/items.lua:  on_refill = technic.refill_RE_charge,
> technic/items.lua:  on_refill = technic.refill_RE_charge,
> technic/tools/sonic_screwdriver.lua:    on_refill = technic.refill_RE_charge,
> technic/tools/prospector.lua:   on_refill = technic.refill_RE_charge,
> technic/tools/flashlight.lua:   on_refill = technic.refill_RE_charge,
> technic/tools/mining_lasers.lua:        on_refill = technic.refill_RE_charge,
> technic/tools/cans.lua:     on_refill = function(stack)
> technic/tools/mining_lasers.lua~:       on_refill = technic.refill_RE_charge,
> technic/tools/chainsaw.lua: on_refill = technic.refill_RE_charge,
> technic/tools/mining_drill.lua: on_refill = technic.refill_RE_charge,
> technic/tools/mining_drill.lua: on_refill = technic.refill_RE_charge,
> technic/tools/mining_drill.lua:     on_refill = technic.refill_RE_charge,
> technic/tools/mining_drill.lua: on_refill = technic.refill_RE_charge,
> technic/tools/mining_drill.lua:     on_refill = technic.refill_RE_charge,

grep -r on_refill

> technic/helpers.lua:function technic.refill_RE_charge(stack)
> technic/machines/register/battery_box.lua:  on_refill = technic.refill_RE_charge,
> technic/items.lua:  on_refill = technic.refill_RE_charge,
> technic/items.lua:  on_refill = technic.refill_RE_charge,
> technic/items.lua:  on_refill = technic.refill_RE_charge,
> technic/tools/sonic_screwdriver.lua:    on_refill = technic.refill_RE_charge,
> technic/tools/prospector.lua:   on_refill = technic.refill_RE_charge,
> technic/tools/flashlight.lua:   on_refill = technic.refill_RE_charge,
> technic/tools/mining_lasers.lua:        on_refill = technic.refill_RE_charge,
> technic/tools/mining_lasers.lua~:       on_refill = technic.refill_RE_charge,
> technic/tools/chainsaw.lua: on_refill = technic.refill_RE_charge,
> technic/tools/mining_drill.lua: on_refill = technic.refill_RE_charge,
> technic/tools/mining_drill.lua: on_refill = technic.refill_RE_charge,
> technic/tools/mining_drill.lua:     on_refill = technic.refill_RE_charge,
> technic/tools/mining_drill.lua: on_refill = technic.refill_RE_charge,
> technic/tools/mining_drill.lua:     on_refill = technic.refill_RE_charge,

l think l better add technic.refill_RE_charge to moretechnictools, too

**Comment by ExcaliburZero** [comment]
Okay, that sounds good. I'll merge it.

**Comment by HybridDog** [comment]
thanks

**Pull request merged**
